// Monte Carlo, Monaco — real-world coordinates (approximate, city-block accuracy)
const PLACES = [
  { id: "louis-xv",            name: "Le Louis XV",                category: "dining",   lat: 43.7394, lng: 7.4270, img: "imgs/le_louis_xv.png",            photo: "imgs/le_louis_xv_v2.png",            blurb: "Alain Ducasse's three-Michelin-star dining room inside the Hôtel de Paris." },
  { id: "casino",               name: "Casino de Monte-Carlo",      category: "tour",     lat: 43.7392, lng: 7.4276, img: "imgs/casino_monte_carlo.png",      photo: "imgs/casino_monte_carlo_v2.png",     blurb: "The gilded gaming halls that put Monte-Carlo on the map." },
  { id: "port",                 name: "Port Hercule",               category: "tour",     lat: 43.7332, lng: 7.4225, img: "imgs/port_hercule.png",            photo: "imgs/port_hercule_v2.png",           blurb: "Superyachts and Grand Prix straights line Monaco's storied harbour." },
  { id: "musee",                name: "Musée Océanographique",      category: "tour",     lat: 43.7325, lng: 7.4256, img: "imgs/musee_oceanographique.png",   photo: "imgs/musee_oceanographique_v2.png",  blurb: "A cliffside aquarium founded by Prince Albert I in 1910." },
  { id: "jardin-japonais",      name: "Jardin Japonais de Monaco",  category: "tour",     lat: 43.7377, lng: 7.4304, img: "imgs/jardin_japonais.png",         photo: "imgs/jardin_japonais_v2.png",        blurb: "A pocket of Kyoto calm along the Monte-Carlo seafront." },
  { id: "circuit",              name: "Circuit de Monaco",          category: "tour",     lat: 43.7368, lng: 7.4297, img: "imgs/circuit_de_monaco.png",       photo: "imgs/circuit_de_monaco_v2.png",      blurb: "The very tarmac the Formula 1 field races each May." },
  { id: "palais",               name: "Palais Princier",            category: "tour",     lat: 43.7314, lng: 7.4177, img: "imgs/palais_princier.png",         photo: "imgs/palais_princier_v2.png",        blurb: "Home to the Grimaldi family since the 13th century." },
  { id: "garnier",              name: "Salle Garnier",              category: "tour",     lat: 43.7396, lng: 7.4278, img: "imgs/salle_garnier.png",           photo: "imgs/salle_garnier_v2.png",          blurb: "The opera house designed by Charles Garnier, of Paris Opéra fame." },
  { id: "cafe-de-paris",        name: "Café de Paris Monte-Carlo",  category: "dining",   lat: 43.7395, lng: 7.4276, img: "imgs/cafe_de_paris.png",           photo: "imgs/cafe_de_paris_v2.png",          blurb: "Belle Époque people-watching across from the Casino steps." },
  { id: "le-grill",             name: "Le Grill",                   category: "dining",   lat: 43.7393, lng: 7.4271, img: "imgs/le_grill.png",                photo: "imgs/le_grill_v2.png",               blurb: "Rooftop dining with a retractable roof and sweeping harbour views." },
  { id: "rampoldi",             name: "Rampoldi",                   category: "dining",   lat: 43.7384, lng: 7.4288, img: "imgs/rampoldi.png",                photo: "imgs/rampoldi_v2.png",               blurb: "An old-guard Monégasque table serving classic Italian fare since 1946." },
  { id: "jardin-exotique",      name: "Jardin Exotique de Monaco",  category: "tour",     lat: 43.7326, lng: 7.4136, img: "imgs/jardin_exotique.png",         photo: "imgs/jardin_exotique_v2.png",        blurb: "Cactus gardens clinging to the cliffside, with caves below." },
  { id: "fort-antoine",         name: "Fort Antoine",               category: "tour",     lat: 43.7301, lng: 7.4222, img: "imgs/fort_antoine.png",            photo: "imgs/fort_antoine_v2.png",           blurb: "An 18th-century fort turned open-air summer theatre." },
  { id: "marche-condamine",     name: "Marché de la Condamine",     category: "shopping", lat: 43.7346, lng: 7.4208, img: "imgs/marche_condamine.png",        photo: "imgs/marche_condamine_v2.png",       blurb: "The morning market for Monaco's fruit, flowers, and flavour." },
  { id: "one-monte-carlo",      name: "One Monte-Carlo",            category: "shopping", lat: 43.7386, lng: 7.4266, img: "imgs/one_monte_carlo.png",         photo: "imgs/one_monte_carlo_v2.png",        blurb: "A quiet, high-end shopping quarter minutes from the Casino." },
  { id: "metropole-shopping",   name: "Metropole Shopping Center",  category: "shopping", lat: 43.7382, lng: 7.4283, img: "imgs/metropole_shopping.png",      photo: "imgs/metropole_shopping_v2.png",     blurb: "Designer boutiques under a Karl Lagerfeld-designed atrium." },
];

const MAP_CENTER = { lat: 43.7362, lng: 7.4250 };
